require 'roles_generic'
require 'require_all'    
require 'set'
require 'sugar-high/array'
require 'rails'
require 'arel'
require 'meta_where'
require 'yaml'
require 'logger'

require 'roles_active_record/namespaces'
require 'roles_active_record/base'
require 'roles_active_record/strategy'
